[lib]
crate-type = ["cdylib"]

[package]
name = "fluid_sim_wasm"
version = "0.1.0"
edition = "2024"

[dependencies]
js-sys = "0.3.77"
wasm-bindgen = "0.2.100"
web-sys = { version = "0.3.77", features = ["console"] }
